name: yellowstone-directed
favicon: null
layout_spectrum: 0.48
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#cdc5bd'
    - '#292220'
    - '#a7a092'
    - '#917a5f'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: follow
    item: null
    url: null
